package com.beijing.geek.cms.sys.domain.common;

import java.util.Date;

public class SysTimetask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timetask.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timetask.cron_expression
     *
     * @mbggenerated
     */
    private String cronExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timetask.is_effect
     *
     * @mbggenerated
     */
    private String isEffect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timetask.is_start
     *
     * @mbggenerated
     */
    private String isStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timetask.task_describe
     *
     * @mbggenerated
     */
    private String taskDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timetask.task_code
     *
     * @mbggenerated
     */
    private String taskCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timetask.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timetask.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timetask.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timetask.modified
     *
     * @mbggenerated
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timetask.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timetask.task_id
     *
     * @return the value of sys_timetask.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timetask.task_id
     *
     * @param taskId the value for sys_timetask.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timetask.cron_expression
     *
     * @return the value of sys_timetask.cron_expression
     *
     * @mbggenerated
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timetask.cron_expression
     *
     * @param cronExpression the value for sys_timetask.cron_expression
     *
     * @mbggenerated
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timetask.is_effect
     *
     * @return the value of sys_timetask.is_effect
     *
     * @mbggenerated
     */
    public String getIsEffect() {
        return isEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timetask.is_effect
     *
     * @param isEffect the value for sys_timetask.is_effect
     *
     * @mbggenerated
     */
    public void setIsEffect(String isEffect) {
        this.isEffect = isEffect == null ? null : isEffect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timetask.is_start
     *
     * @return the value of sys_timetask.is_start
     *
     * @mbggenerated
     */
    public String getIsStart() {
        return isStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timetask.is_start
     *
     * @param isStart the value for sys_timetask.is_start
     *
     * @mbggenerated
     */
    public void setIsStart(String isStart) {
        this.isStart = isStart == null ? null : isStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timetask.task_describe
     *
     * @return the value of sys_timetask.task_describe
     *
     * @mbggenerated
     */
    public String getTaskDescribe() {
        return taskDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timetask.task_describe
     *
     * @param taskDescribe the value for sys_timetask.task_describe
     *
     * @mbggenerated
     */
    public void setTaskDescribe(String taskDescribe) {
        this.taskDescribe = taskDescribe == null ? null : taskDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timetask.task_code
     *
     * @return the value of sys_timetask.task_code
     *
     * @mbggenerated
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timetask.task_code
     *
     * @param taskCode the value for sys_timetask.task_code
     *
     * @mbggenerated
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode == null ? null : taskCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timetask.creator
     *
     * @return the value of sys_timetask.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timetask.creator
     *
     * @param creator the value for sys_timetask.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timetask.created
     *
     * @return the value of sys_timetask.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timetask.created
     *
     * @param created the value for sys_timetask.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timetask.modifier
     *
     * @return the value of sys_timetask.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timetask.modifier
     *
     * @param modifier the value for sys_timetask.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timetask.modified
     *
     * @return the value of sys_timetask.modified
     *
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timetask.modified
     *
     * @param modified the value for sys_timetask.modified
     *
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timetask.deleted
     *
     * @return the value of sys_timetask.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timetask.deleted
     *
     * @param deleted the value for sys_timetask.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}