package com.beijing.geek.cms.sys.dao.common;

import com.beijing.geek.cms.sys.domain.common.AttrQueryParam;
import com.beijing.geek.cms.sys.domain.common.SysAttrValue;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysAttrValueDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attr_value
     *
     * @param attrValue
     * @mbggenerated
     */
    int deleteById(SysAttrValue attrValue)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attr_value
     *
     * @mbggenerated
     */
    int insert(SysAttrValue record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attr_value
     *
     * @mbggenerated
     */
    SysAttrValue selectById(Integer attrId)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attr_value
     *
     * @mbggenerated
     */
    int updateById(SysAttrValue record)throws Exception;

    /**
     * 根据属性Code查询属性列表
     *
     * @param groupCode
     * @return
     * @throws Exception
     */
    List<SysAttrValue> selectByAttrGroupCode(@Param("groupCode") String groupCode) throws Exception;

    /**
     * 查询属性列表数量
     *
     * @param param
     * @return
     * @throws Exception
     */
    Integer selectAttrCountByPage(AttrQueryParam param) throws Exception;

    /**
     * 查询属性列表
     *
     * @param param
     * @return
     * @throws Exception
     */
    List<SysAttrValue> selectAttrListByPage(AttrQueryParam param) throws Exception;
}