package com.beijing.geek.cms.sys.domain.common;

public class SysIconWithBLOBs extends SysIcon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_icon.content
     *
     * @mbggenerated
     */
    private byte[] content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_icon.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_icon.content
     *
     * @return the value of sys_icon.content
     *
     * @mbggenerated
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_icon.content
     *
     * @param content the value for sys_icon.content
     *
     * @mbggenerated
     */
    public void setContent(byte[] content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_icon.path
     *
     * @return the value of sys_icon.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_icon.path
     *
     * @param path the value for sys_icon.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}