package com.beijing.geek.cms.sys.domain.user;

import java.util.Date;

public class SysDataRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_rule.data_rule_id
     *
     * @mbggenerated
     */
    private Integer dataRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_rule.rule_name
     *
     * @mbggenerated
     */
    private String ruleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_rule.rule_column
     *
     * @mbggenerated
     */
    private String ruleColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_rule.rule_conditions
     *
     * @mbggenerated
     */
    private String ruleConditions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_rule.rule_value
     *
     * @mbggenerated
     */
    private String ruleValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_rule.function_Id
     *
     * @mbggenerated
     */
    private String functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_rule.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_rule.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_rule.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_rule.modified
     *
     * @mbggenerated
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_rule.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_rule.data_rule_id
     *
     * @return the value of sys_data_rule.data_rule_id
     *
     * @mbggenerated
     */
    public Integer getDataRuleId() {
        return dataRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_rule.data_rule_id
     *
     * @param dataRuleId the value for sys_data_rule.data_rule_id
     *
     * @mbggenerated
     */
    public void setDataRuleId(Integer dataRuleId) {
        this.dataRuleId = dataRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_rule.rule_name
     *
     * @return the value of sys_data_rule.rule_name
     *
     * @mbggenerated
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_rule.rule_name
     *
     * @param ruleName the value for sys_data_rule.rule_name
     *
     * @mbggenerated
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_rule.rule_column
     *
     * @return the value of sys_data_rule.rule_column
     *
     * @mbggenerated
     */
    public String getRuleColumn() {
        return ruleColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_rule.rule_column
     *
     * @param ruleColumn the value for sys_data_rule.rule_column
     *
     * @mbggenerated
     */
    public void setRuleColumn(String ruleColumn) {
        this.ruleColumn = ruleColumn == null ? null : ruleColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_rule.rule_conditions
     *
     * @return the value of sys_data_rule.rule_conditions
     *
     * @mbggenerated
     */
    public String getRuleConditions() {
        return ruleConditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_rule.rule_conditions
     *
     * @param ruleConditions the value for sys_data_rule.rule_conditions
     *
     * @mbggenerated
     */
    public void setRuleConditions(String ruleConditions) {
        this.ruleConditions = ruleConditions == null ? null : ruleConditions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_rule.rule_value
     *
     * @return the value of sys_data_rule.rule_value
     *
     * @mbggenerated
     */
    public String getRuleValue() {
        return ruleValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_rule.rule_value
     *
     * @param ruleValue the value for sys_data_rule.rule_value
     *
     * @mbggenerated
     */
    public void setRuleValue(String ruleValue) {
        this.ruleValue = ruleValue == null ? null : ruleValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_rule.function_Id
     *
     * @return the value of sys_data_rule.function_Id
     *
     * @mbggenerated
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_rule.function_Id
     *
     * @param functionId the value for sys_data_rule.function_Id
     *
     * @mbggenerated
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId == null ? null : functionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_rule.creator
     *
     * @return the value of sys_data_rule.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_rule.creator
     *
     * @param creator the value for sys_data_rule.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_rule.created
     *
     * @return the value of sys_data_rule.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_rule.created
     *
     * @param created the value for sys_data_rule.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_rule.modifier
     *
     * @return the value of sys_data_rule.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_rule.modifier
     *
     * @param modifier the value for sys_data_rule.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_rule.modified
     *
     * @return the value of sys_data_rule.modified
     *
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_rule.modified
     *
     * @param modified the value for sys_data_rule.modified
     *
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_rule.deleted
     *
     * @return the value of sys_data_rule.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_rule.deleted
     *
     * @param deleted the value for sys_data_rule.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}