package com.beijing.geek.cms.sys.dao.common;

import com.beijing.geek.cms.sys.domain.common.SysAttrGroup;

import java.util.List;

public interface SysAttrGroupDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attr_group
     *
     * @mbggenerated
     */
    int deleteById(Integer attrGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attr_group
     *
     * @mbggenerated
     */
    int insert(SysAttrGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attr_group
     *
     * @mbggenerated
     */
    int insertSelective(SysAttrGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attr_group
     *
     * @mbggenerated
     */
    SysAttrGroup selectById(Integer attrGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attr_group
     *
     * @mbggenerated
     */
    int updateByIdSelective(SysAttrGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attr_group
     *
     * @mbggenerated
     */
    int updateById(SysAttrGroup record);

    /**
     * 查询属性组列表
     *
     * @return
     * @throws Exception
     */
    List<SysAttrGroup> selectAllList() throws Exception;

}