package com.beijing.geek.cms.sys.dao.user;

import com.beijing.geek.cms.sys.domain.user.RoleQueryParam;
import com.beijing.geek.cms.sys.domain.user.SysRole;

import java.util.List;

public interface SysRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated
     * @param role
     */
    int deleteById(SysRole role)throws Exception;


    int insert(SysRole record) throws Exception;

    SysRole selectById(Integer roleId) throws Exception;


    int updateById(SysRole record) throws Exception;

    /**
     * 查询分页数量
     *
     * @param param
     * @return
     * @throws Exception
     */
    Integer selectRoleCountByPage(RoleQueryParam param) throws Exception;

    /**
     * 查询角色列表
     *
     * @param param
     * @return
     * @throws Exception
     */
    List<SysRole> selectRoleListByPage(RoleQueryParam param) throws Exception;


}