package com.beijing.geek.cms.sys.dao.common;

import com.beijing.geek.cms.sys.domain.common.SysTimetask;

public interface SysTimetaskDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_timetask
     *
     * @mbggenerated
     */
    int deleteById(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_timetask
     *
     * @mbggenerated
     */
    int insert(SysTimetask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_timetask
     *
     * @mbggenerated
     */
    int insertSelective(SysTimetask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_timetask
     *
     * @mbggenerated
     */
    SysTimetask selectById(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_timetask
     *
     * @mbggenerated
     */
    int updateByIdSelective(SysTimetask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_timetask
     *
     * @mbggenerated
     */
    int updateById(SysTimetask record);
}