package com.beijing.geek.cms.sys.dao.user;

import com.beijing.geek.cms.sys.domain.user.SysDataRule;

public interface SysDataRuleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_rule
     *
     * @mbggenerated
     */
    int deleteById(Integer dataRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_rule
     *
     * @mbggenerated
     */
    int insert(SysDataRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_rule
     *
     * @mbggenerated
     */
    int insertSelective(SysDataRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_rule
     *
     * @mbggenerated
     */
    SysDataRule selectById(Integer dataRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_rule
     *
     * @mbggenerated
     */
    int updateByIdSelective(SysDataRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_rule
     *
     * @mbggenerated
     */
    int updateById(SysDataRule record);
}