package com.beijing.geek.cms.sys.domain.user;

import java.util.Date;

public class SysRegion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.region_id
     *
     * @mbggenerated
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.region_name
     *
     * @mbggenerated
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.parent_region_id
     *
     * @mbggenerated
     */
    private Integer parentRegionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.region_post_code
     *
     * @mbggenerated
     */
    private String regionPostCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.region_code
     *
     * @mbggenerated
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.modified
     *
     * @mbggenerated
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.region_id
     *
     * @return the value of sys_region.region_id
     *
     * @mbggenerated
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.region_id
     *
     * @param regionId the value for sys_region.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.region_name
     *
     * @return the value of sys_region.region_name
     *
     * @mbggenerated
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.region_name
     *
     * @param regionName the value for sys_region.region_name
     *
     * @mbggenerated
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.parent_region_id
     *
     * @return the value of sys_region.parent_region_id
     *
     * @mbggenerated
     */
    public Integer getParentRegionId() {
        return parentRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.parent_region_id
     *
     * @param parentRegionId the value for sys_region.parent_region_id
     *
     * @mbggenerated
     */
    public void setParentRegionId(Integer parentRegionId) {
        this.parentRegionId = parentRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.region_post_code
     *
     * @return the value of sys_region.region_post_code
     *
     * @mbggenerated
     */
    public String getRegionPostCode() {
        return regionPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.region_post_code
     *
     * @param regionPostCode the value for sys_region.region_post_code
     *
     * @mbggenerated
     */
    public void setRegionPostCode(String regionPostCode) {
        this.regionPostCode = regionPostCode == null ? null : regionPostCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.region_code
     *
     * @return the value of sys_region.region_code
     *
     * @mbggenerated
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.region_code
     *
     * @param regionCode the value for sys_region.region_code
     *
     * @mbggenerated
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.creator
     *
     * @return the value of sys_region.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.creator
     *
     * @param creator the value for sys_region.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.created
     *
     * @return the value of sys_region.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.created
     *
     * @param created the value for sys_region.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.modifier
     *
     * @return the value of sys_region.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.modifier
     *
     * @param modifier the value for sys_region.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.modified
     *
     * @return the value of sys_region.modified
     *
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.modified
     *
     * @param modified the value for sys_region.modified
     *
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.deleted
     *
     * @return the value of sys_region.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.deleted
     *
     * @param deleted the value for sys_region.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}