package com.beijing.geek.cms.sunshine.domain;

import java.util.Date;

public class TbRoomType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.type_id
     *
     * @mbg.generated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.num_rooms
     *
     * @mbg.generated
     */
    private Integer numRooms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.price_1
     *
     * @mbg.generated
     */
    private Double price1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.price_2
     *
     * @mbg.generated
     */
    private Double price2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.sale_price_1
     *
     * @mbg.generated
     */
    private Double salePrice1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.sale_price_2
     *
     * @mbg.generated
     */
    private Double salePrice2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.price_note
     *
     * @mbg.generated
     */
    private String priceNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.bad_type
     *
     * @mbg.generated
     */
    private String badType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.breakfast
     *
     * @mbg.generated
     */
    private String breakfast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.network
     *
     * @mbg.generated
     */
    private String network;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.floor
     *
     * @mbg.generated
     */
    private String floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.type_note
     *
     * @mbg.generated
     */
    private String typeNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.c_time
     *
     * @mbg.generated
     */
    private Date cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.u_time
     *
     * @mbg.generated
     */
    private Date uTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room_type.del_status
     *
     * @mbg.generated
     */
    private Integer delStatus;
    private String env;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.type_id
     *
     * @return the value of tb_room_type.type_id
     * @mbg.generated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.type_id
     *
     * @param typeId the value for tb_room_type.type_id
     * @mbg.generated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.type_name
     *
     * @return the value of tb_room_type.type_name
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.type_name
     *
     * @param typeName the value for tb_room_type.type_name
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.num_rooms
     *
     * @return the value of tb_room_type.num_rooms
     * @mbg.generated
     */
    public Integer getNumRooms() {
        return numRooms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.num_rooms
     *
     * @param numRooms the value for tb_room_type.num_rooms
     * @mbg.generated
     */
    public void setNumRooms(Integer numRooms) {
        this.numRooms = numRooms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.price_1
     *
     * @return the value of tb_room_type.price_1
     * @mbg.generated
     */
    public Double getPrice1() {
        return price1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.price_1
     *
     * @param price1 the value for tb_room_type.price_1
     * @mbg.generated
     */
    public void setPrice1(Double price1) {
        this.price1 = price1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.price_2
     *
     * @return the value of tb_room_type.price_2
     * @mbg.generated
     */
    public Double getPrice2() {
        return price2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.price_2
     *
     * @param price2 the value for tb_room_type.price_2
     * @mbg.generated
     */
    public void setPrice2(Double price2) {
        this.price2 = price2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.sale_price_1
     *
     * @return the value of tb_room_type.sale_price_1
     * @mbg.generated
     */
    public Double getSalePrice1() {
        return salePrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.sale_price_1
     *
     * @param salePrice1 the value for tb_room_type.sale_price_1
     * @mbg.generated
     */
    public void setSalePrice1(Double salePrice1) {
        this.salePrice1 = salePrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.sale_price_2
     *
     * @return the value of tb_room_type.sale_price_2
     * @mbg.generated
     */
    public Double getSalePrice2() {
        return salePrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.sale_price_2
     *
     * @param salePrice2 the value for tb_room_type.sale_price_2
     * @mbg.generated
     */
    public void setSalePrice2(Double salePrice2) {
        this.salePrice2 = salePrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.price_note
     *
     * @return the value of tb_room_type.price_note
     * @mbg.generated
     */
    public String getPriceNote() {
        return priceNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.price_note
     *
     * @param priceNote the value for tb_room_type.price_note
     * @mbg.generated
     */
    public void setPriceNote(String priceNote) {
        this.priceNote = priceNote == null ? null : priceNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.bad_type
     *
     * @return the value of tb_room_type.bad_type
     * @mbg.generated
     */
    public String getBadType() {
        return badType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.bad_type
     *
     * @param badType the value for tb_room_type.bad_type
     * @mbg.generated
     */
    public void setBadType(String badType) {
        this.badType = badType == null ? null : badType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.breakfast
     *
     * @return the value of tb_room_type.breakfast
     * @mbg.generated
     */
    public String getBreakfast() {
        return breakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.breakfast
     *
     * @param breakfast the value for tb_room_type.breakfast
     * @mbg.generated
     */
    public void setBreakfast(String breakfast) {
        this.breakfast = breakfast == null ? null : breakfast.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.network
     *
     * @return the value of tb_room_type.network
     * @mbg.generated
     */
    public String getNetwork() {
        return network;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.network
     *
     * @param network the value for tb_room_type.network
     * @mbg.generated
     */
    public void setNetwork(String network) {
        this.network = network == null ? null : network.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.floor
     *
     * @return the value of tb_room_type.floor
     * @mbg.generated
     */
    public String getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.floor
     *
     * @param floor the value for tb_room_type.floor
     * @mbg.generated
     */
    public void setFloor(String floor) {
        this.floor = floor == null ? null : floor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.type_note
     *
     * @return the value of tb_room_type.type_note
     * @mbg.generated
     */
    public String getTypeNote() {
        return typeNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.type_note
     *
     * @param typeNote the value for tb_room_type.type_note
     * @mbg.generated
     */
    public void setTypeNote(String typeNote) {
        this.typeNote = typeNote == null ? null : typeNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.comment
     *
     * @return the value of tb_room_type.comment
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.comment
     *
     * @param comment the value for tb_room_type.comment
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.c_time
     *
     * @return the value of tb_room_type.c_time
     * @mbg.generated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.c_time
     *
     * @param cTime the value for tb_room_type.c_time
     * @mbg.generated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.u_time
     *
     * @return the value of tb_room_type.u_time
     * @mbg.generated
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.u_time
     *
     * @param uTime the value for tb_room_type.u_time
     * @mbg.generated
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room_type.del_status
     *
     * @return the value of tb_room_type.del_status
     * @mbg.generated
     */
    public Integer getDelStatus() {
        return delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room_type.del_status
     *
     * @param delStatus the value for tb_room_type.del_status
     * @mbg.generated
     */
    public void setDelStatus(Integer delStatus) {
        this.delStatus = delStatus;
    }

    public String getEnv() {
        return env;
    }

    public void setEnv(String env) {
        this.env = env;
    }
}