package com.beijing.geek.cms.sunshine.domain;

import java.util.Date;

public class TbOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.type_id
     *
     * @mbg.generated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.init_id
     *
     * @mbg.generated
     */
    private Integer initId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_num_rooms
     *
     * @mbg.generated
     */
    private Integer orderNumRooms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_status
     *
     * @mbg.generated
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.end_date
     *
     * @mbg.generated
     */
    private Date endDate;
    private String startDateStr;
    private String endDateStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.late_arri_time
     *
     * @mbg.generated
     */
    private String lateArriTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.sum_price
     *
     * @mbg.generated
     */
    private Double sumPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.sum_sale_price
     *
     * @mbg.generated
     */
    private Double sumSalePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.c_time
     *
     * @mbg.generated
     */
    private Date cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.u_time
     *
     * @mbg.generated
     */
    private Date uTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.del_status
     *
     * @mbg.generated
     */
    private Integer delStatus;
    private String checkCount;
    private Date orderDate;
    private Date confirmDate;
    private String env;
    private String orderDateStr;
    private String confirmDateStr;
    private String typeName;
    private String company;

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.id
     *
     * @return the value of tb_order.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.id
     *
     * @param id the value for tb_order.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.type_id
     *
     * @return the value of tb_order.type_id
     * @mbg.generated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.type_id
     *
     * @param typeId the value for tb_order.type_id
     * @mbg.generated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.init_id
     *
     * @return the value of tb_order.init_id
     * @mbg.generated
     */
    public Integer getInitId() {
        return initId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.init_id
     *
     * @param initId the value for tb_order.init_id
     * @mbg.generated
     */
    public void setInitId(Integer initId) {
        this.initId = initId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_num_rooms
     *
     * @return the value of tb_order.order_num_rooms
     * @mbg.generated
     */
    public Integer getOrderNumRooms() {
        return orderNumRooms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_num_rooms
     *
     * @param orderNumRooms the value for tb_order.order_num_rooms
     * @mbg.generated
     */
    public void setOrderNumRooms(Integer orderNumRooms) {
        this.orderNumRooms = orderNumRooms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_status
     *
     * @return the value of tb_order.order_status
     * @mbg.generated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_status
     *
     * @param orderStatus the value for tb_order.order_status
     * @mbg.generated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.username
     *
     * @return the value of tb_order.username
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.username
     *
     * @param username the value for tb_order.username
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.telephone
     *
     * @return the value of tb_order.telephone
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.telephone
     *
     * @param telephone the value for tb_order.telephone
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.email
     *
     * @return the value of tb_order.email
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.email
     *
     * @param email the value for tb_order.email
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.start_date
     *
     * @return the value of tb_order.start_date
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.start_date
     *
     * @param startDate the value for tb_order.start_date
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.end_date
     *
     * @return the value of tb_order.end_date
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.end_date
     *
     * @param endDate the value for tb_order.end_date
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.late_arri_time
     *
     * @return the value of tb_order.late_arri_time
     * @mbg.generated
     */
    public String getLateArriTime() {
        return lateArriTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.late_arri_time
     *
     * @param lateArriTime the value for tb_order.late_arri_time
     * @mbg.generated
     */
    public void setLateArriTime(String lateArriTime) {
        this.lateArriTime = lateArriTime == null ? null : lateArriTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.sum_price
     *
     * @return the value of tb_order.sum_price
     * @mbg.generated
     */
    public Double getSumPrice() {
        return sumPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.sum_price
     *
     * @param sumPrice the value for tb_order.sum_price
     * @mbg.generated
     */
    public void setSumPrice(Double sumPrice) {
        this.sumPrice = sumPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.sum_sale_price
     *
     * @return the value of tb_order.sum_sale_price
     * @mbg.generated
     */
    public Double getSumSalePrice() {
        return sumSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.sum_sale_price
     *
     * @param sumSalePrice the value for tb_order.sum_sale_price
     * @mbg.generated
     */
    public void setSumSalePrice(Double sumSalePrice) {
        this.sumSalePrice = sumSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.comment
     *
     * @return the value of tb_order.comment
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.comment
     *
     * @param comment the value for tb_order.comment
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.c_time
     *
     * @return the value of tb_order.c_time
     * @mbg.generated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.c_time
     *
     * @param cTime the value for tb_order.c_time
     * @mbg.generated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.u_time
     *
     * @return the value of tb_order.u_time
     * @mbg.generated
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.u_time
     *
     * @param uTime the value for tb_order.u_time
     * @mbg.generated
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.del_status
     *
     * @return the value of tb_order.del_status
     * @mbg.generated
     */
    public Integer getDelStatus() {
        return delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.del_status
     *
     * @param delStatus the value for tb_order.del_status
     * @mbg.generated
     */
    public void setDelStatus(Integer delStatus) {
        this.delStatus = delStatus;
    }

    public String getCheckCount() {
        return checkCount;
    }

    public void setCheckCount(String checkCount) {
        this.checkCount = checkCount;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public Date getConfirmDate() {
        return confirmDate;
    }

    public void setConfirmDate(Date confirmDate) {
        this.confirmDate = confirmDate;
    }

    public String getEnv() {
        return env;
    }

    public void setEnv(String env) {
        this.env = env;
    }

    public String getStartDateStr() {
        return startDateStr;
    }

    public void setStartDateStr(String startDateStr) {
        this.startDateStr = startDateStr;
    }

    public String getEndDateStr() {
        return endDateStr;
    }

    public void setEndDateStr(String endDateStr) {
        this.endDateStr = endDateStr;
    }

    public String getOrderDateStr() {
        return orderDateStr;
    }

    public void setOrderDateStr(String orderDateStr) {
        this.orderDateStr = orderDateStr;
    }

    public String getConfirmDateStr() {
        return confirmDateStr;
    }

    public void setConfirmDateStr(String confirmDateStr) {
        this.confirmDateStr = confirmDateStr;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
}