package com.beijing.geek.cms.sys.domain.common;

import java.util.Date;

public class SysAttrValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_value.attr_id
     *
     * @mbggenerated
     */
    private Integer attrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_value.attr_group_id
     *
     * @mbggenerated
     */
    private Integer attrGroupId;
    private String attrGroupName;
    private String attrGroupCode;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_value.attr_code
     *
     * @mbggenerated
     */
    private String attrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_value.attr_value
     *
     * @mbggenerated
     */
    private String attrValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_value.attr_order
     *
     * @mbggenerated
     */
    private Integer attrOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_value.attr_desc
     *
     * @mbggenerated
     */
    private String attrDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_value.creator
     *
     * @mbggenerated
     */
    private Integer creator;
    private String creatorName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_value.created
     *
     * @mbggenerated
     */
    private Date created;
    private String createdStr;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_value.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_value.modified
     *
     * @mbggenerated
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_value.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_value.attr_id
     *
     * @return the value of sys_attr_value.attr_id
     * @mbggenerated
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_value.attr_id
     *
     * @param attrId the value for sys_attr_value.attr_id
     * @mbggenerated
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_value.attr_group_id
     *
     * @return the value of sys_attr_value.attr_group_id
     * @mbggenerated
     */
    public Integer getAttrGroupId() {
        return attrGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_value.attr_group_id
     *
     * @param attrGroupId the value for sys_attr_value.attr_group_id
     * @mbggenerated
     */
    public void setAttrGroupId(Integer attrGroupId) {
        this.attrGroupId = attrGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_value.attr_code
     *
     * @return the value of sys_attr_value.attr_code
     * @mbggenerated
     */
    public String getAttrCode() {
        return attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_value.attr_code
     *
     * @param attrCode the value for sys_attr_value.attr_code
     * @mbggenerated
     */
    public void setAttrCode(String attrCode) {
        this.attrCode = attrCode == null ? null : attrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_value.attr_value
     *
     * @return the value of sys_attr_value.attr_value
     * @mbggenerated
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_value.attr_value
     *
     * @param attrValue the value for sys_attr_value.attr_value
     * @mbggenerated
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue == null ? null : attrValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_value.attr_order
     *
     * @return the value of sys_attr_value.attr_order
     * @mbggenerated
     */
    public Integer getAttrOrder() {
        return attrOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_value.attr_order
     *
     * @param attrOrder the value for sys_attr_value.attr_order
     * @mbggenerated
     */
    public void setAttrOrder(Integer attrOrder) {
        this.attrOrder = attrOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_value.attr_desc
     *
     * @return the value of sys_attr_value.attr_desc
     * @mbggenerated
     */
    public String getAttrDesc() {
        return attrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_value.attr_desc
     *
     * @param attrDesc the value for sys_attr_value.attr_desc
     * @mbggenerated
     */
    public void setAttrDesc(String attrDesc) {
        this.attrDesc = attrDesc == null ? null : attrDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_value.creator
     *
     * @return the value of sys_attr_value.creator
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_value.creator
     *
     * @param creator the value for sys_attr_value.creator
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_value.created
     *
     * @return the value of sys_attr_value.created
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_value.created
     *
     * @param created the value for sys_attr_value.created
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_value.modifier
     *
     * @return the value of sys_attr_value.modifier
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_value.modifier
     *
     * @param modifier the value for sys_attr_value.modifier
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_value.modified
     *
     * @return the value of sys_attr_value.modified
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_value.modified
     *
     * @param modified the value for sys_attr_value.modified
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_value.deleted
     *
     * @return the value of sys_attr_value.deleted
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_value.deleted
     *
     * @param deleted the value for sys_attr_value.deleted
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    public String getAttrGroupName() {
        return attrGroupName;
    }

    public void setAttrGroupName(String attrGroupName) {
        this.attrGroupName = attrGroupName;
    }

    public String getAttrGroupCode() {
        return attrGroupCode;
    }

    public void setAttrGroupCode(String attrGroupCode) {
        this.attrGroupCode = attrGroupCode;
    }

    public String getCreatorName() {
        return creatorName;
    }

    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    public String getCreatedStr() {
        return createdStr;
    }

    public void setCreatedStr(String createdStr) {
        this.createdStr = createdStr;
    }
}