package com.beijing.geek.cms.sys.domain.common;
import java.util.Date;

public class SysAttrGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_group.attr_group_id
     *
     * @mbggenerated
     */
    private Integer attrGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_group.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_group.group_code
     *
     * @mbggenerated
     */
    private String groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_group.group_desc
     *
     * @mbggenerated
     */
    private String groupDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_group.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_group.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_group.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_group.modified
     *
     * @mbggenerated
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attr_group.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_group.attr_group_id
     *
     * @return the value of sys_attr_group.attr_group_id
     *
     * @mbggenerated
     */
    public Integer getAttrGroupId() {
        return attrGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_group.attr_group_id
     *
     * @param attrGroupId the value for sys_attr_group.attr_group_id
     *
     * @mbggenerated
     */
    public void setAttrGroupId(Integer attrGroupId) {
        this.attrGroupId = attrGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_group.group_name
     *
     * @return the value of sys_attr_group.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_group.group_name
     *
     * @param groupName the value for sys_attr_group.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_group.group_code
     *
     * @return the value of sys_attr_group.group_code
     *
     * @mbggenerated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_group.group_code
     *
     * @param groupCode the value for sys_attr_group.group_code
     *
     * @mbggenerated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_group.group_desc
     *
     * @return the value of sys_attr_group.group_desc
     *
     * @mbggenerated
     */
    public String getGroupDesc() {
        return groupDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_group.group_desc
     *
     * @param groupDesc the value for sys_attr_group.group_desc
     *
     * @mbggenerated
     */
    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc == null ? null : groupDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_group.creator
     *
     * @return the value of sys_attr_group.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_group.creator
     *
     * @param creator the value for sys_attr_group.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_group.created
     *
     * @return the value of sys_attr_group.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_group.created
     *
     * @param created the value for sys_attr_group.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_group.modifier
     *
     * @return the value of sys_attr_group.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_group.modifier
     *
     * @param modifier the value for sys_attr_group.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_group.modified
     *
     * @return the value of sys_attr_group.modified
     *
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_group.modified
     *
     * @param modified the value for sys_attr_group.modified
     *
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attr_group.deleted
     *
     * @return the value of sys_attr_group.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attr_group.deleted
     *
     * @param deleted the value for sys_attr_group.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}