package com.beijing.geek.cms.sys.domain.common;

import java.util.Date;

public class SysIcon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_icon.icon_id
     *
     * @mbggenerated
     */
    private Integer iconId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_icon.extend
     *
     * @mbggenerated
     */
    private String extend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_icon.iconclas
     *
     * @mbggenerated
     */
    private String iconclas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_icon.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_icon.type
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_icon.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_icon.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_icon.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_icon.modified
     *
     * @mbggenerated
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_icon.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_icon.icon_id
     *
     * @return the value of sys_icon.icon_id
     *
     * @mbggenerated
     */
    public Integer getIconId() {
        return iconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_icon.icon_id
     *
     * @param iconId the value for sys_icon.icon_id
     *
     * @mbggenerated
     */
    public void setIconId(Integer iconId) {
        this.iconId = iconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_icon.extend
     *
     * @return the value of sys_icon.extend
     *
     * @mbggenerated
     */
    public String getExtend() {
        return extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_icon.extend
     *
     * @param extend the value for sys_icon.extend
     *
     * @mbggenerated
     */
    public void setExtend(String extend) {
        this.extend = extend == null ? null : extend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_icon.iconclas
     *
     * @return the value of sys_icon.iconclas
     *
     * @mbggenerated
     */
    public String getIconclas() {
        return iconclas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_icon.iconclas
     *
     * @param iconclas the value for sys_icon.iconclas
     *
     * @mbggenerated
     */
    public void setIconclas(String iconclas) {
        this.iconclas = iconclas == null ? null : iconclas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_icon.name
     *
     * @return the value of sys_icon.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_icon.name
     *
     * @param name the value for sys_icon.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_icon.type
     *
     * @return the value of sys_icon.type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_icon.type
     *
     * @param type the value for sys_icon.type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_icon.creator
     *
     * @return the value of sys_icon.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_icon.creator
     *
     * @param creator the value for sys_icon.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_icon.created
     *
     * @return the value of sys_icon.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_icon.created
     *
     * @param created the value for sys_icon.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_icon.modifier
     *
     * @return the value of sys_icon.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_icon.modifier
     *
     * @param modifier the value for sys_icon.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_icon.modified
     *
     * @return the value of sys_icon.modified
     *
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_icon.modified
     *
     * @param modified the value for sys_icon.modified
     *
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_icon.deleted
     *
     * @return the value of sys_icon.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_icon.deleted
     *
     * @param deleted the value for sys_icon.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}